nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: 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

npmScopes:
  decafteam:
    npmRegistryServer: 'https://npm.pkg.github.com'
