nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: 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

npmScopes:
  decafteam:
    npmRegistryServer: "https://npm.pkg.github.com"
