nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: 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

npmScopes:
  decafteam:
    npmRegistryServer: 'https://npm.pkg.github.com'
