export const MANUAL_STELLAR_TOKENS = [
  {
    symbol: 'USDC',
    name: 'USD Coin',
    address: 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
    coingeckoId: 'usd-coin',
    coincodex: 'usd-coin',
  },
  {
    symbol: 'yUSDC',
    name: 'Ultra Stellar USD',
    address: 'GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF',
    coingeckoId: 'usd-coin',
    coincodex: 'yusdc',
  },
  {
    symbol: 'USDS',
    name: 'Stably USD',
    address: 'GBK4AYTOYIAYT4UJECSQGMACUWLKYOOM4VCAUUZ3Y3FG5XD2LYK3FGK2',
    coingeckoId: 'usd-coin',
    coincodex: 'stableusd',
  },
  {
    symbol: 'EURT',
    name: 'EURT Euro',
    address: 'GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S',
    coingeckoId: 'euro-coin',
    coincodex: 'eurt-token',
  },
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    address: 'GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5',
    coingeckoId: 'bitcoin',
    coincodex: 'bitcoin',
  },
  {
    symbol: 'yXLM',
    name: 'Ultra Stellar Lumens',
    address: 'GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55',
    coingeckoId: 'stellar',
    coincodex: 'yxlm',
  },
  {
    symbol: 'LSP',
    name: 'Lumenswap',
    address: 'GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK',
    logoURI: 'https://lumenswap.io/t/Lumenswap144.png',
    coingeckoId: 'lumenswap',
    coincodex: 'lumenswap',
  },
  {
    symbol: 'BTCLN',
    name: 'kbtrading BTC LN',
    address: 'GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT',
    coingeckoId: 'bitcoin',
    coincodex: 'bitcoinlightning',
  },
  {
    symbol: 'AFR',
    name: 'Afreum',
    address: 'GBX6YI45VU7WNAAKA3RBFDR3I3UKNFHTJPQ5F6KOOKSGYIAM4TRQN54W',
    coingeckoId: 'afreum',
    coincodex: 'afreum',
  },
  {
    symbol: 'XRP',
    name: 'Ripple',
    address: 'GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P',
    coingeckoId: 'xrp',
    coincodex: 'ripple',
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    address: 'GBFXOHVAS43OIWNIO7XLRJAHT3BICFEIKOJLZVXNT572MISM4CMGSOCC',
    coingeckoId: 'ethereum',
    coincodex: 'ethereum',
  },
  {
    symbol: 'MXN',
    name: 'anchormxn MXN',
    address: 'GCKIK5F6J4KMKF6MKB5EM67S5CK557EZQ3IAMZM5FFAYST63S3HWXVPE',
    coingeckoId: 'mexican-peso-tether',
    coincodex: 'anchormxn',
  },
  {
    symbol: 'ETH',
    name: 'Interstellar ETH',
    address: 'GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P',
    coingeckoId: 'ethereum',
    coincodex: 'ethereum',
  },
  {
    symbol: 'yETH',
    name: 'Ultra Stellar Ethereum',
    address: 'GDYQNEF2UWTK4L6HITMT53MZ6F5QWO3Q4UVE6SCGC4OMEQIZQQDERQFD',
    coingeckoId: 'ethereum',
    coincodex: 'yeth',
  },
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    address: 'GDPJALI4AZKUU2W426U5WKMAT6CN3AJRPIIRYR2YM54TL2GDWO5O2MZM',
    coingeckoId: 'bitcoin',
    coincodex: 'bitcoin',
  },
  {
    symbol: 'XRP',
    name: 'StellarPort XRP',
    address: 'GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5',
    coingeckoId: 'xrp',
    coincodex: 'ripple',
  },
  {
    symbol: 'yBTC',
    name: 'Ultra Stellar Bitcoin',
    address: 'GBUVRNH4RW4VLHP4C5MOF46RRIRZLAVHYGX45MVSTKA2F6TMR7E7L6NW',
    coingeckoId: 'bitcoin',
    coincodex: 'ybtc',
  },
  {
    symbol: 'BTC',
    name: 'InterStellar BTC',
    address: 'GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P',
    coingeckoId: 'bitcoin',
    coincodex: 'bitcoin',
  },
  {
    symbol: 'BTC',
    address: 'GCQVEST7KIWV3KOSNDDUJKEPZLBFWKM7DUS4TCLW2VNVPCBGTDRVTEIT',
    coingeckoId: 'bitcoin',
    coincodex: 'bitcoin',
  },
  {
    symbol: 'ETH',
    name: 'Coinqvest ETH',
    address: 'GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5',
    coingeckoId: 'ethereum',
    coincodex: 'ethereum',
  },
  {
    symbol: 'AQUA',
    name: 'Aquarius',
    address: 'GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA',
    coingeckoId: 'aquarius',
    coincodex: 'aquarius',
  },
];
